///////////////////////////////////////////////////////////////////////////////
// ExampleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Example = 0x3F000000;
#define SRVNAME_EXAMPLE "Example"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ExampleCExample = {0xb6ed1202,0x02b9,0x4014,{0x9c,0x60,0x93,0xf5,0xf8,0xf8,0x8d,0xa3}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ExampleTolerance = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ExampleInputs
{
	ULONG ExampleId;
} ExampleInputs, *PExampleInputs;

typedef struct _ExampleOutputs
{
	struct {
		double time;
		double pos[3];
		double vel[3];
	} MotionOutput;
	ULONGLONG ExampleId;
	double SumDiff;
	double EffectiveTolerance;
} ExampleOutputs, *PExampleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ExampleInputs 0
#define ADI_ExampleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
