///////////////////////////////////////////////////////////////////////////////
// ExampleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Example = 0x3F000000;
#define SRVNAME_EXAMPLE "Example"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ExampleCExample = {0xb6ed1202,0x02b9,0x4014,{0x9c,0x60,0x93,0xf5,0xf8,0xf8,0x8d,0xa3}};
const CTCID CID_ExampleCInterpolator1D = {0xb26dd069,0x8b84,0x44ec,{0x84,0xff,0x19,0x15,0x83,0x24,0xca,0x1b}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ExampleTolerance = 0x00000001;
const PTCID PID_Interpolator1DParameter = 0x00000001;
const PTCID PID_Interpolator1DTask = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_8C991C59_73E7_4FE2_B3D2_9BB7E5CB841D_INCLUDED_)
#define _TC_TYPE_8C991C59_73E7_4FE2_B3D2_9BB7E5CB841D_INCLUDED_
typedef struct _State
{
	double Time;
	double Position;
	double Velocity;
	double Acceleration;
} State, *PState;
#endif // !defined(_TC_TYPE_8C991C59_73E7_4FE2_B3D2_9BB7E5CB841D_INCLUDED_)

typedef struct _ExampleInputs
{
	ULONG ExampleId;
} ExampleInputs, *PExampleInputs;

typedef struct _ExampleOutputs
{
	struct {
		double time;
		double pos[3];
		double vel[3];
	} MotionOutput;
	ULONGLONG ExampleId;
	double SumDiff;
	double EffectiveTolerance;
} ExampleOutputs, *PExampleOutputs;

typedef struct _Interpolator1DParameter
{
	double max_velocity;
	double max_acceleration;
	double max_jerk;
} Interpolator1DParameter, *PInterpolator1DParameter;

typedef struct _Interpolator1DInputs
{
	double InitialPosition;
	double InitialVelocity;
} Interpolator1DInputs, *PInterpolator1DInputs;

typedef struct _Interpolator1DOutputs
{
	State PositionControlState;
	State VelocityControlState;
} Interpolator1DOutputs, *PInterpolator1DOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ExampleInputs 0
#define ADI_ExampleOutputs 1
#define ADI_Interpolator1DInputs 0
#define ADI_Interpolator1DOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
