///////////////////////////////////////////////////////////////////////////////
// Interpolator1D.h
#pragma once

#include "ExampleInterfaces.h"
#include "interpolator1d/interpolator.hh"

class CInterpolator1D 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CInterpolator1D();
	virtual	~CInterpolator1D();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	Interpolator1DParameter m_Parameter;
	ULONG m_CycleTime;
	Interpolator1DInputs m_Inputs;
	Interpolator1DOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcTaskPtr m_spTask;
///</AutoGeneratedContent>

	PositionInterpolator1D m_PositionInterpolator;
	VelocityInterpolator1D m_VelocityInterpolator;
	PositionInterpolator1D::State m_CurrentStatePos;
	VelocityInterpolator1D::State m_CurrentStateVel;
};
